fix README.md configuration issue
fix the "Accessing Kafka with internal and external clients" configuration

otherwise exception will be throw at kafka container start:

ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.IllegalArgumentException: requirement failed: inter.broker.listener.name must be a listener name defined in advertised.listeners. The valid options based on currently configured listeners are CLIENT,EXTERNAL